const palette = {
  // palette
  danger: "#f7142a",
  default: "#5c646f",
  info: "#0dcaf0",
  link: "#36b4f0",
  muted: "#999999",
  primary: "#d3121a",
  primaryDark: "#7e090e",
  primaryLight: "#df6f74",
  success: "#41b341",
  warning: "#ffc107",
};

const colors = {
  buttonBackgroundColor: "#c0cedf",
  buttonTextColor: "#0c0c0c",

  light: {
    activityIndicatorColor: palette.primary,
    autoCompleteListBorderColor: "#dddfe2",
    autoCompleteListBackgroundColor: "#f5f5f5",
    autoCompleteListHeaderBackgroundColor: "#ffffff",
    cardBackgroundColor: "#ffffff",
    clearIconColor: "#b3beca",
    drawerHeaderBackgroundColor: null,
    drawerActiveBackgroundColor: "#f5f5f5",
    drawerActiveTintColor: palette.primary,
    // drawerInactiveBackgroundColor: palette.primaryDark,
    drawerInactiveTintColor: "#0c0c0c",
    formLabelColor: "black",
    highPriorityBackgroundColor: "#eb1c24",
    inputIconColor: "#4e4e4e",
    lineSeparatorColor: "#c4d0dd",
    modalBackgroundColor: "#ffffff",
    modalBorderColor: "#cccccc",
    modalTitleColor: "black",
    navigationTextColor: palette.primary,
    navigationBackgroundColor: "#ffffff",
    overlayBackgroundColor: "rgba(185,185,185,0.75)",
    highlightColor: "#f5f5f5",
    placeholderTextColor: "lightgray",
    screenBackgroundColor: "#ecedf0",
    shadowColor: "gray",
    // order status colors
    statusColors: {
      completed: "#179e17",
      default: "#5c646f",
      due: "#f7c64a",
      inProgress: "#f73def",
      new: "#0c0c0c",
      overdue: "#f7142a",
      pending: "#f7af3e",
      unassigned: "#1baaee",
    },
    tabBackgroundColor: "#ffffff",
    tabBarBorderTopColor: "#f5f5f5",
    tabBarInactiveTintColor: "gray",
    textColor: "#0c0c0c",
    textInputBorderColor: "#dddfe2",
    textInputColor: "#0c0c0c",
    textInputBackgroundColor: "#f5f5f5",
    textLinkColor: palette.link,
    topTabBarIndicatorColor: "#ffffff",
    topTabBarActiveTintColor: "#ffffff",
    topTabBarBackgroundColor: palette.primary,
    topTabBarInactiveTintColor: "lightgray",
  },
  dark: {
    activityIndicatorColor: palette.primary,
    autoCompleteListBorderColor: "#777777",
    autoCompleteListBackgroundColor: "#2c3139",
    autoCompleteListHeaderBackgroundColor: "#000000",
    cardBackgroundColor: "#2e353e",
    clearIconColor: "#4a525f",
    drawerHeaderBackgroundColor: null,
    drawerActiveBackgroundColor: "#1f242b",
    drawerActiveTintColor: palette.primary,
    // drawerInactiveBackgroundColor: palette.primaryDark,
    drawerInactiveTintColor: "#c4d0dd",
    formLabelColor: "#f6a821",
    highPriorityBackgroundColor: "darkred",
    inputIconColor: "#b3beca",
    lineSeparatorColor: "#444c5a",
    modalBackgroundColor: "#2e353e",
    modalBorderColor: "#0c0c0c",
    modalTitleColor: "#ffffff",
    navigationTextColor: "#ffffff",
    navigationBackgroundColor: palette.primary,
    overlayBackgroundColor: "rgba(90, 102, 114, 0.75)",
    highlightColor: "#1f242b",
    placeholderTextColor: "gray",
    screenBackgroundColor: "#1d2127",
    shadowColor: "gray",
    // order status colors
    statusColors: {
      completed: "#179e17",
      default: "#5c646f",
      due: "#f7c64a",
      inProgress: "#f73def",
      new: "#c4d0dd",
      overdue: "#f7142a",
      pending: "#f7af3e",
      unassigned: "#1baaee",
    },
    tabBackgroundColor: "black",
    tabBarBorderTopColor: "#333333",
    tabBarInactiveTintColor: "gray",
    textColor: "#c4d0dd",
    textInputBorderColor: "#0c0c0c",
    textInputColor: "#c4d0dd",
    textInputBackgroundColor: "#2c3139",
    textLinkColor: palette.link,
    topTabBarIndicatorColor: palette.primaryDark,
    topTabBarActiveTintColor: "#ffffff",
    topTabBarBackgroundColor: "black",
    topTabBarInactiveTintColor: "gray",
  },
};

export { colors, palette };
